name: Build and Release JARs (Java 8, 11, 17, 21)

on:
  workflow_dispatch:    # 支持手动触发
  push:                 # push时自动触发
    branches:
      - main
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact (JDK${{ matrix.java }})
        uses: actions/upload-artifact@v4
        with:
          name: Dumper-java${{ matrix.java }}
          path: target/*.jar

      - name: Set output for jar file
        id: jar
        run: |
          echo "jar_path=$(ls target/*with-dependencies.jar | head -n 1)" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          files: ${{ steps.jar.outputs.jar_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
