name: Build and Release JARs (Java 8, 11, 17, 21)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    outputs:
      matrix: ${{ toJson(matrix.java) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact (Java${{ matrix.java }})
        uses: actions/upload-artifact@v4
        with:
          name: dumper-java${{ matrix.java }}
          path: target/*with-dependencies.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-jars
  
      - name: Create Release Tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          TAG="auto-release-$(date +'%Y%m%d-%H%M%S')"
          git tag $TAG
          git push origin $TAG
          echo "tag_name=$TAG" >> $GITHUB_ENV
  
      - name: Upload all JARs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: all-jars/**/*
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
